version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "192.168.1.134:1883:1883" # må gjere IP dynamisk
      - "192.168.1.134:9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

networks:
  default:
    name: mqtt5-network
